### ISSUE TITLE
Investigate Mullvad DNS-hijacking issues

### ISSUE THREAD

**Issue by schnerring** [schnerring/schnerring.github.io#36]
- Do some digging in https://github.com/mullvad/mullvadvpn-app source code
- Test which DNS servers are affected by DNS hijacking

**Comment by schnerring** [comment]
The [Mullvad API has changed and requires DNS-hijacking to be disabled per "Mullvad device" on creation](https://github.com/mullvad/mullvadvpn-app/issues/473#issuecomment-1500461798). They also added an API endpoint to easily rotate keys for Mullvad devices. I'll have to update this article because most of the endpoints used have been deprecated.

**Comment by schnerring** [comment]
Update `curl` commands that interact with the Mullvad API

**Comment by dmorin20** [comment]
Found this information as I'm trying to run mullvad with unbound. Currently having a little trouble getting this set up as I am a novice at this. Is it possible to create a wireguard config for the router with dns hijacking turned off for my specific location?

**Comment by schnerring** [comment]
> Found this information as I'm trying to run mullvad with unbound. Currently having a little trouble getting this set up as I am a novice at this. Is it possible to create a wireguard config for the router with dns hijacking turned off for my specific location?

https://schnerring.net/blog/use-custom-dns-servers-with-mullvad-and-any-wireguard-client/#tldr
